# Generated by Django 3.2.3 on 2021-06-28 05:53

import app_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='facebook',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='github',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='instagram',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='linkedin',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twitter',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(upload_to=app_auth.models.image_location),
        ),
    ]
